# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a27440602ef1df8c23327b21a0062446174f229457b880b9cab5e900e91d5254e30b698c1c8443ed8434ad49c56e4ffb1404b24800ab5dfcf642d7b50949e44f

test:
  secret_key_base: 2f60b114425ef0ea6b026602f8d4771f6a664efc928cff5ff2a86df21f0295e6070499ba875f89474de3df3a4ff3add61576f586752b713c5d060e799f6d8659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
